/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-06 07:33:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch16.lecture._01tag;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class _13navbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5 (1).jar", Long.valueOf(1680653773016L));
    _jspx_dependants.put("jar:file:/C:/study/jsp/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jsp/WEB-INF/lib/taglibs-standard-impl-1.2.5%20(1).jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/tags/mytag13.tag", Long.valueOf(1680766411575L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_d_005fmytag13_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<div class=\"container-lg mt-3\" >\r\n");
      out.write("		<h1>About</h1>\r\n");
      out.write("		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque voluptas veritatis voluptate eos odio laudantium esse reprehenderit. Error nulla omnis ad accusamus aspernatur similique quam doloribus quos quidem inventore labore.</p>\r\n");
      out.write("		<h1>Dolorum eos molestiae.</h1>\r\n");
      out.write("		<p>Nostrum accusantium dolorum magni aspernatur recusandae illo quia deserunt aut quo molestias repellat qui. Molestias quisquam maxime velit obcaecati asperiores quidem commodi sed ipsa reprehenderit voluptatem perspiciatis nobis natus illum!</p>\r\n");
      out.write("		<h1>Eius veniam facilis.</h1>\r\n");
      out.write("		<p>Quisquam quod maiores voluptatum laboriosam magni ipsa quo rerum error odit voluptatibus itaque possimus ipsam ea soluta beatae. Iusto omnis voluptate possimus maxime impedit autem ducimus ea nostrum repellendus officia!</p>\r\n");
      out.write("		<h1>Animi dolores consectetur!</h1>\r\n");
      out.write("		<p>Quo dolores inventore perspiciatis cupiditate est id sed ipsam velit nostrum ad ex vero iure rem excepturi ea minus labore delectus magni quis consequatur! Minus asperiores optio perspiciatis ab cum!</p>\r\n");
      out.write("		<h1>Quibusdam velit harum.</h1>\r\n");
      out.write("		<p>Aperiam sapiente provident nam harum laudantium doloremque nobis ducimus recusandae suscipit quaerat eos optio explicabo ipsum! Sequi perferendis similique distinctio labore aliquid illum ea nobis reprehenderit aut accusamus quo incidunt.</p>\r\n");
      out.write("		<h1>Nemo aliquid sed.</h1>\r\n");
      out.write("		<p>Dolores animi aperiam placeat. Repellat ullam in laborum cumque voluptatum voluptatibus dolorem aut nam odit. Molestias incidunt porro ipsum quo asperiores suscipit nisi in odio debitis itaque eaque quibusdam velit.</p>\r\n");
      out.write("		<h1>Voluptatum officia iusto.</h1>\r\n");
      out.write("		<p>Harum obcaecati quidem ab eveniet autem perspiciatis id hic aliquid amet incidunt. Libero enim optio nobis odit adipisci error rerum possimus. Quibusdam temporibus explicabo aut cumque placeat vero blanditiis aspernatur.</p>\r\n");
      out.write("		<h1>Nobis ipsam similique.</h1>\r\n");
      out.write("		<p>Velit ipsum eligendi illo molestias magnam numquam dignissimos asperiores debitis voluptas cum tempora distinctio odio sint dolorum eum soluta quia eaque eos delectus dolores nemo quis maxime aperiam itaque quidem.</p>\r\n");
      out.write("		<h1>Exercitationem rerum delectus.</h1>\r\n");
      out.write("		<p>Rerum repellat debitis reprehenderit quae fugiat cupiditate aspernatur eos eum id iure incidunt magni illum ipsam vel unde non veritatis natus accusantium fugit iste molestiae ut nam voluptate ipsum ea?</p>\r\n");
      out.write("		<h1>Autem dolore eveniet?</h1>\r\n");
      out.write("		<p>Dolores voluptas incidunt aperiam laudantium nisi at maiores ab facere reprehenderit blanditiis nobis molestiae officiis. Sint dolor voluptatibus iure repellat praesentium id ad officia veritatis vel laboriosam corporis necessitatibus nobis!</p>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_d_005fmytag13_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  d:mytag13
    org.apache.jsp.tag.web.mytag13_tag _jspx_th_d_005fmytag13_005f0 = new org.apache.jsp.tag.web.mytag13_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_d_005fmytag13_005f0);
    try {
      _jspx_th_d_005fmytag13_005f0.setJspContext(_jspx_page_context);
      // /ch16/lecture/01tag/13navbar.jsp(15,1) name = active type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_d_005fmytag13_005f0.setActive("about");
      _jspx_th_d_005fmytag13_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_d_005fmytag13_005f0);
    }
    return false;
  }
}
